version: '3'
# Это пример для кластера swarm с локальным репозиторием
# start with command: docker stack deploy --restart=always -c docker-compose.yaml [stack_name]
#
services:
 app1:
    build: .
    image: 127.0.0.1:5000/rest-example:latest
    ports:
      - '9999:8888'
    deploy:
       restart_policy:
         condition: any
         delay: 5s
         max_attempts: 3
         window: 30s
       mode: replicated
       replicas: 5
# просто для примера: в stack можно запускать несколько приложений сразу
 redis:
    image: 127.0.0.1:5000/redis
    deploy:
       restart_policy:
         condition: any
         delay: 5s
         max_attempts: 3
         window: 30s
       mode: replicated
       replicas: 1
 web:
    image: 127.0.0.1:5000/nginx
    ports:
      - '8080:80'
    command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
      mode: replicated
      replicas: 2
#